services:
  templatedb:
    image: postgres:13.3-alpine
    restart: always
    container_name: postgres_template
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apm
networks:
  apm:
    external: true