// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gaogao-asia/golang-template/internal/account/handler"
	"github.com/gaogao-asia/golang-template/internal/account/repository"
	"github.com/gaogao-asia/golang-template/internal/account/service"
	"github.com/gaogao-asia/golang-template/internal/client"
)

// Injectors from account_di.go:
func InitAccountHandler() *handler.AccountHandler {
	db := initDB()
	accountRepository := repository.NewAccountRepository(db)
	accountService := service.NewAccountService(accountRepository)

	productClient := client.NewProductClient()
	accountHandler := handler.NewAccountHandler(accountService, productClient)
	return accountHandler
}
