// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/gaogao-asia/golang-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, acc
func (_m *AccountService) CreateAccount(ctx context.Context, acc *domain.Account) error {
	ret := _m.Called(ctx, acc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, acc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *domain.Account
func (_e *AccountService_Expecter) CreateAccount(ctx interface{}, acc interface{}) *AccountService_CreateAccount_Call {
	return &AccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, acc)}
}

func (_c *AccountService_CreateAccount_Call) Run(run func(ctx context.Context, acc *domain.Account)) *AccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Account))
	})
	return _c
}

func (_c *AccountService_CreateAccount_Call) Return(_a0 error) *AccountService_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_CreateAccount_Call) RunAndReturn(run func(context.Context, *domain.Account) error) *AccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function with given fields: ctx
func (_m *AccountService) GetAccounts(ctx context.Context) ([]*domain.Account, error) {
	ret := _m.Called(ctx)

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type AccountService_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AccountService_Expecter) GetAccounts(ctx interface{}) *AccountService_GetAccounts_Call {
	return &AccountService_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx)}
}

func (_c *AccountService_GetAccounts_Call) Run(run func(ctx context.Context)) *AccountService_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AccountService_GetAccounts_Call) Return(_a0 []*domain.Account, _a1 error) *AccountService_GetAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_GetAccounts_Call) RunAndReturn(run func(context.Context) ([]*domain.Account, error)) *AccountService_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
