server:
  port: ':8000'
  name: 'gotemplate'
database:
  postgres:
    host: 'localhost'
    port: 5431
    user: 'template'
    dbname: 'templatedb'
monitor:
  opentelemetry:
    enable: false
  tempo:
    endpoint: localhost:4317