x-logging:
  &logging
  driver: loki # shipping stdout to loki. In k8s, we can use fluentbit|promtail instead
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    loki-batch-size: 10485762
    loki-min-backoff: 1s
services:
  productservice:
    logging: *logging
    image: productservice
    container_name: productservice
    ports:
      - "8100:8100"
    environment:
      - APPENV=CONTAINER
    networks:
      - apm

networks:
  apm:
    external: true