{
 "title": "SIRO",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total registed users",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_users{instance=\"siro_reception:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (siro_reception_times_count{instance=\"siro_reception:8000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NO. Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(path) (siro_reception_hits{instance=\"siro_reception:8000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, path) (rate(siro_reception_times_bucket{instance=\"siro_reception:8000\"}[24h]))) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}